# Generated by Django 6.0.1 on 2026-01-28 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeeprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='bank_account_iban',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='commercial_record',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('VENDOR', 'Vendor'), ('ATTENDEE', 'Attendee')], default='ATTENDEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='organization_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
