# Generated by Django 6.0.1 on 2026-02-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_attendeeprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('VENDOR', 'Vendor'), ('ATTENDEE', 'Attendee'), ('SCEGA_ADMIN', 'SCEGA Admin')], default='ATTENDEE', max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('age_restriction', models.PositiveIntegerField(default=0, help_text='Minimum age required (0 for no restriction)')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('approval', models.CharField(choices=[('PENDING', 'Pending License'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organizerprofile')),
            ],
        ),
    ]
